var _lang_default = 'en';

try{
    let language = window.parent.document.getElementById('mindmap_diagram_language');
    console.log("kityminder language: ", language.value);
    if(language != null){
        _lang_default = language.value;
    }
}catch(e){}

var _lang_pack = {
    'en': {
        'template': {
            'default': 'Kityminder',
            'tianpan': 'Sky chart',
            'structure': 'Organization Chart',
            'filetree': 'Directory Organization Chart',
            'right': 'Logical structure Diagram',
            'fish-bone': 'Fishbone Diagram'
        },
        'hotbox': {
            'undo': 'Undo',
            'redo': 'Redo',
            'appendsiblingnode': 'Sibling',
            'appendparentnode': 'Parent',
            'appendchildnode': 'Child',
            'editnode': 'Edit',
            'arrangeup': 'Up',
            'arrangedown': 'Down',
            'resetlayout': 'Reset',
            'remove': 'Remove',
            'priority': 'Priority',
            'progress': 'Progress',
            'importnode': 'Import Node',
            'exportnode': 'Export Node'
        },
        'theme': {
            'classic': 'Classic',
            'classic-compact': 'Compact',
            'snow': 'Snow',
            'snow-compact': 'Snow Comp',
            'fish': 'Fishbone',
            'wire': 'Wire',
            'fresh-red': 'Red',
            'fresh-soil': 'Soil',
            'fresh-green': 'Green',
            'fresh-blue': 'Blue',
            'fresh-purple': 'Purple',
            'fresh-pink': 'Pink',
            'fresh-red-compat': 'Red Comp',
            'fresh-soil-compat': 'Soil Comp',
            'fresh-green-compat': 'Green Comp',
            'fresh-blue-compat': 'Blue Comp',
            'fresh-purple-compat': 'Purple Comp',
            'fresh-pink-compat': 'Pink Comp',
            'tianpan': 'Sky Chart',
            'tianpan-compact': 'Sky Comp'
        },
        'maintopic': 'Main Topic',
        'topic': 'Topic',
        'panels': {
            'history': 'History',
            'template': 'Template',
            'theme': 'Theme',
            'layout': 'Layout',
            'style': 'Style',
            'font': 'Font',
            'color': 'Color',
            'background': 'Background',
            'insert': 'Insert',
            'arrange': 'Arrange',
            'nodeop': 'Nodeop',
            'priority': 'Priority',
            'progress': 'Progress',
            'resource': 'Resource',
            'note': 'Note',
            'attachment': 'Attachment',
            'word': 'Word'
        },
        'error_message': {
            'title': 'Oops, the Mindmap is error',
            'err_load': 'Load Mindmap failed',
            'err_save': 'Save Mindmap failed',
            'err_network': 'Network error',
            'err_doc_resolve': 'Resolve document failed',
            'err_unknown': 'Unknown error',
            'err_localfile_read': 'Local file read error',
            'err_download': 'Download failed',
            'err_remove_share': 'Share remove failed',
            'err_create_share': 'Share create failed',
            'err_mkdir': 'Folder creation failed',
            'err_ls': 'Folder read failed',
            'err_share_data': 'Shared data error',
            'err_share_sync_fail': 'Shared data sync failed',
            'err_move_file': 'File move failed',
            'err_rename': 'Rename failed',

            'unknownreason': 'Maybe aliens tampered with the code...',
            'pcs_code': {
                3: "This interface is not supported",
                4: "Do not have permission to perform this operation",
                5: "IP unauthorized",
                110: "User session has expired, please log in again",
                31001: "Database query error",
                31002: "Database connection error",
                31003: "Database returns empty results",
                31021: "Network Error",
                31022: "Unable to connect to server",
                31023: "Input parameter error",
                31024: "App id is empty",
                31025: "Backend storage error",
                31041: "User's cookie is not a legitimate Baidu cookie",
                31042: "User is not logged in",
                31043: "User not activated",
                31044: "User not authorized",
                31045: "User does not exist",
                31046: "User already exists",
                31061: "The file already exists",
                31062: "Illegal filename",
                31063: "File parent directory does not exist",
                31064: "Not authorized to access this file",
                31065: "The directory is full",
                31066: "File does not exist",
                31067: "Error processing file",
                31068: "File creation failed",
                31069: "File copy failed",
                31070: "File deletion failed",
                31071: "Cannot read file meta information",
                31072: "File move failed",
                31073: "File renaming failed",
                31079: "File MD5 not found, please upload the entire file using the upload API.",
                31081: "Failed to create superfile",
                31082: "Superfile block list is empty",
                31083: "Superfile update failed",
                31101: "Internal error in tag system",
                31102: "Tag parameter error",
                31103: "Tag system error",
                31110: "Not authorized to set quota for this directory",
                31111: "Quota management only supports two levels of directories",
                31112: "Exceeded quota",
                31113: "Quota cannot exceed quota for directory ancestors",
                31114: "Quota cannot be smaller than subdirectory quota",
                31141: "Failed to request thumbnail service",
                31201: "Signature error",
                31202: "The file does not exist",
                31203: "Failed to set ACL",
                31204: "Request ACL validation failed",
                31205: "Failed to get ACL",
                31206: "ACL does not exist",
                31207: "bucket already exists",
                31208: "User request error",
                31209: "Server Error",
                31210: "Server not supported",
                31211: "Access forbidden",
                31212: "Service unavailable",
                31213: "Error retrying",
                31214: "Failed to upload file data",
                31215: "Failed to upload file meta",
                31216: "Failed to download file data",
                31217: "Failed to download file meta",
                31218: "Capacity exceeded",
                31219: "The number of requests exceeded the limit",
                31220: "Traffic limit exceeded",
                31298: "The server return value KEY is invalid",
                31299: "Server return value KEY does not exist"
            }
        },
        'ui': {
            'shared_file_title': '[Shared] {0} (read only)',
            'load_share_for_edit': 'Loading shared file...',
            'share_sync_success': 'Shared content has been synchronized',
            'recycle_clear_confirm': 'Confirm to clear the recycle bin? Empty files cannot be recovered. ',
            'fullscreen_exit_hint': 'Press Esc or F11 to exit fullscreen',
            'error_detail': 'Details',
            'copy_and_feedback': 'Copy and Feedback',
            'move_file_confirm': 'Are you sure to move "{0}" to "{1}" ？',
            'rename': 'Rename',
            'rename_success': '{0} rename succeeded',
            'move_success': '{0} moved successfully to {1}',
            'command': {
                'appendsiblingnode': 'Sibling Node',
                'appendparentnode': 'Parent Node',
                'appendchildnode': 'Child Node',
                'removenode': 'Remove',
                'editnode': 'Edit',
                'arrangeup': 'Up',
                'arrangedown': 'Down',
                'resetlayout': 'Reset',
                'expandtoleaf': 'Expand',
                'expandtolevel1': 'Expand to level 1',
                'expandtolevel2': 'Expand to level 2',
                'expandtolevel3': 'Expand to level 3',
                'expandtolevel4': 'Expand to level 4',
                'expandtolevel5': 'Expand to level 5',
                'expandtolevel6': 'Expand to level 6',
                'fullscreen': 'Fullscreen',
                'outline': 'Outline',
                'addtag': 'Add Tip'
            },
            'search': 'Search',
            'expandtoleaf': 'Expand',
            'back': 'Back',
            'undo': 'Undo (Ctrl + Z)',
            'redo': 'Redo (Ctrl + Y)',
            'tabs': {
                'idea': 'Idea',
                'appearence': 'Appearence',
                'view': 'View'
            },
            'quickvisit': {
                'new': 'New (Ctrl + Alt + N)',
                'save': 'Save (Ctrl + S)',
                'share': 'Share (Ctrl + Alt + S)',
                'feedback': 'Feedback（F1）',
                'editshare': 'Edit'
            },
            'menu': {
                'mainmenutext': 'Kity Minder', // 主菜单按钮文本
                'newtab': 'New',
                'opentab': 'Open',
                'savetab': 'Save',
                'sharetab': 'Share',
                'preferencetab': 'Preference',
                'helptab': 'Help',
                'feedbacktab': 'Feedback',
                'recenttab': 'Recent',
                'netdisktab': 'Netdisc',
                'localtab': 'Local',
                'drafttab': 'Draft',
                'downloadtab': 'Download',
                'createsharetab': 'Share',
                'managesharetab': 'My share',

                'newheader': 'New',
                'openheader': 'Open',
                'saveheader': 'Save',
                'draftheader': 'Draft',
                'shareheader': 'Share',
                'downloadheader': 'Download',
                'preferenceheader': 'Preference',
                'helpheader': 'Help',
                'feedbackheader': 'Feedback'
            },

            'mydocument': 'My document',
            'emptydir': 'Empty！',
            'pickfile': 'Select the file...',
            'acceptfile': 'Accept file：{0}',
            'dropfile': 'Drop file',
            'unsupportedfile': 'Unsupported file format',
            'untitleddoc': 'Untitle document',
            'overrideconfirm': '{0} already exists, confirm to overwrite?',
            'checklogin': 'Checking login status...',
            'loggingin': 'Logging in...',
            'recent': 'Recently opened',
            'clearrecent': 'Clear',
            'clearrecentconfirm': 'Confirm to clear recent documents list?',
            'cleardraft': 'Clear',
            'cleardraftconfirm': 'Confirm to clear drafts?',

            'none_share': 'None share',
            'public_share': 'Public share',
            'password_share': 'Private share',
            'email_share': 'Email invitation',
            'url_share': 'Mindmap URL address:',
            'sns_share': 'Social network share:',
            'sns_share_text': '“{0}” - The mind map I made with Baidu Mind Map, check it out! Address：{1}',
            'none_share_description': 'Do not share the current Mindmap',
            'public_share_description': 'Create a share visible to anyone',
            'share_button_text': 'Create',
            'password_share_description': 'Create a share that requires a password to be visible',
            'email_share_description': 'Create a share visible to specified people, you can also allow them to edit',
            'ondev': 'Stay tuned!',
            'create_share_failed': 'Share failed: {0}',
            'remove_share_failed': 'Remove failed: {1}',
            'copy': 'Copy',
            'copied': 'Copied',
            'shared_tip': 'The current mind map is shared by  {0} , you can modify it and save it to your own network disk or share it again',
            'current_share': 'Current mind map',
            'manage_share': 'My Share',
            'share_remove_action': 'Do not share this mind map',
            'share_view_action': 'Open share address',
            'share_edit_action': 'Edit shared file',

            'login': 'Login',
            'logout': 'Logout',
            'switchuser': 'Switch account',
            'userinfo': 'User information',
            'gotonetdisk': 'My Netdisk',
            'requirelogin': 'Please use after <a class="login-button"> login </a> ',
            'saveas': 'Save as',
            'filename': 'Filename',
            'fileformat': 'Save format',
            'save': 'Save',
            'mkdir': 'New directory',
            'recycle': 'Recycle',
            'newdir': 'Untitle directory',

            'bold': 'Bold',
            'italic': 'Italic',
            'forecolor': 'Font color',
            'fontfamily': 'Font family',
            'fontsize': 'Font size',
            'layoutstyle': 'Layout theme',
            'node': 'node',
            'saveto': 'Save as',
            'hand': 'Drag and drop allowed',
            'camera': 'Locate the root node',
            'zoom-in': 'Zoom-in(Ctrl+)',
            'zoom-out': 'Zoom-out(Ctrl-)',
            'markers': 'Markers',
            'resource': 'Resource',
            'help': 'Help',
            'preference': 'Preference',
            'expandnode': 'Expand node',
            'collapsenode': 'Collapse node',
            'template': 'Template',
            'theme': 'Theme',
            'clearstyle': 'Clear',
            'copystyle': 'Copy Style',
            'pastestyle': 'Paste Style',
            'appendsiblingnode': 'Sibling topic',
            'appendchildnode': 'Subordinate topic',
            'arrangeup': 'Arrange up',
            'arrangedown': 'Arrange down',
            'editnode': 'Edit',
            'removenode': 'Remove',
            'priority': 'Priority',
            'removepriority': 'Remove Priority',
            'progress': {
                'p1': 'Not started',
                'p2': 'Complete 1/8',
                'p3': 'Complete 1/4',
                'p4': 'Complete 3/8',
                'p5': 'Half done',
                'p6': 'Complete 5/8',
                'p7': 'Complete 3/4',
                'p8': 'Complete 7/8',
                'p9': 'Completed',
                'p0': 'Clear progress'
            },
            'link': 'Link',
            'image': 'Image',
            'note': 'Note',
            'insertlink': 'Insert link',
            'insertimage': 'Insert image',
            'insertnote': 'Insert note',
            'removelink': 'Remove link',
            'removeimage': 'Remove image',
            'removenote': 'Remove note',
            'resetlayout': 'Reset',

            'justnow': 'Just now',
            'minutesago': '{0} minutes ago',
            'hoursago': '{0} hours ago',
            'yesterday': 'yesterday',
            'daysago': '{0} days ago',
            'longago': 'a long time ago',

            'redirect': 'You are opening the connection {0}，Baidu Mindmap cannot guarantee the security of the connection, do you want to continue? ',
            'navigator': 'Navigator',

            'unsavedcontent': 'The current file has not been saved to the network disk: \n\n{0}\n\n Although the unsaved data will be cached in the draft box, clearing the browser cache will cause the draft box to be cleared. ',

            'shortcuts': 'Shortcuts',
            'contact': 'Contact and Feedback',
            'email': 'Mail group',
            'qq_group': 'QQ group',
            'github_issue': 'Github',
            'baidu_tieba': 'Post Bar',

            'clipboardunsupported': 'Your browser does not support the clipboard, please use the shortcut key to copy',

            'load_success': '{0} loaded successfully',
            'save_success': '{0} has been saved in {1}',
            'autosave_success': '{0} has been autosaved at {1}',

            'selectall': 'Select',
            'selectrevert': 'Reverse',
            'selectsiblings': 'Select siblings',
            'selectlevel': 'Select level',
            'selectpath': 'Select path',
            'selecttree': 'Select subtree'
        },
        'popupcolor': {
            'clearColor': 'Clear color',
            'standardColor': 'Standard Color',
            'themeColor': 'Theme color'
        },
        'dialogs': {
            'markers': {
                'static': {
                    'lang_input_text': 'Text content:',
                    'lang_input_url': 'Link address:',
                    'lang_input_title': 'Title:',
                    'lang_input_target': 'Target a new window:'
                },
                'priority': 'Priority',
                'none': 'None',
                'progress': {
                    'title': 'Progress',
                    'notdone': 'Not done',
                    'done1': 'Done 1/8',
                    'done2': 'Done 1/4',
                    'done3': 'Done 3/8',
                    'done4': 'Done 1/2',
                    'done5': 'Done 5/8',
                    'done6': 'Done 3/4',
                    'done7': 'Done 7/8',
                    'done': 'Done'
                }
            },
            'help': {

            },
            'hyperlink': {},
            'image': {},
            'resource': {}
        },
        'hyperlink': {
            'hyperlink': 'Link...',
            'unhyperlink': 'Remove link'
        },
        'image': {
            'image': 'Image...',
            'removeimage': 'Remove image'
        },
        'marker': {
            'marker': 'Progress/Priority...'
        },
        'resource': {
            'resource': 'Resource...'
        }
    },
    'zh-cn': {
        'template': {
            'default': '思维导图',
            'tianpan': '天盘图',
            'structure': '组织结构图',
            'filetree': '目录组织图',
            'right': '逻辑结构图',
            'fish-bone': '鱼骨头图'
        },
        'hotbox': {
            'undo': '撤销',
            'redo': '重做',
            'appendsiblingnode': '同级',
            'appendparentnode': '上级',
            'appendchildnode': '下级',
            'editnode': '编辑',
            'arrangeup': '上移',
            'arrangedown': '下移',
            'resetlayout': '整理布局',
            'remove': '删除',
            'priority': '优先级',
            'progress': '进度',
            'importnode': '导入节点',
            'exportnode': '导出节点'
        },
        'theme': {
            'classic': '脑图经典',
            'classic-compact': '紧凑经典',
            'snow': '温柔冷光',
            'snow-compact': '紧凑冷光',
            'fish': '鱼骨图',
            'wire': '线框',
            'fresh-red': '清新红',
            'fresh-soil': '泥土黄',
            'fresh-green': '文艺绿',
            'fresh-blue': '天空蓝',
            'fresh-purple': '浪漫紫',
            'fresh-pink': '脑残粉',
            'fresh-red-compat': '紧凑红',
            'fresh-soil-compat': '紧凑黄',
            'fresh-green-compat': '紧凑绿',
            'fresh-blue-compat': '紧凑蓝',
            'fresh-purple-compat': '紧凑紫',
            'fresh-pink-compat': '紧凑粉',
            'tianpan': '经典天盘',
            'tianpan-compact': '紧凑天盘'
        },
        'maintopic': '中心主题',
        'topic': '分支主题',
        'panels': {
            'history': '历史',
            'template': '模板',
            'theme': '皮肤',
            'layout': '布局',
            'style': '样式',
            'font': '文字',
            'color': '颜色',
            'background': '背景',
            'insert': '插入',
            'arrange': '调整',
            'nodeop': '当前',
            'priority': '优先级',
            'progress': '进度',
            'resource': '资源',
            'note': '备注',
            'attachment': '附件',
            'word': '文字'
        },
        'error_message': {
            'title': '哎呀，脑图出错了',
            'err_load': '加载脑图失败',
            'err_save': '保存脑图失败',
            'err_network': '网络错误',
            'err_doc_resolve': '文档解析失败',
            'err_unknown': '发生了奇怪的错误',
            'err_localfile_read': '文件读取错误',
            'err_download': '文件下载失败',
            'err_remove_share': '取消分享失败',
            'err_create_share': '分享失败',
            'err_mkdir': '目录创建失败',
            'err_ls': '读取目录失败',
            'err_share_data': '加载分享内容出错',
            'err_share_sync_fail': '分享内容同步失败',
            'err_move_file': '文件移动失败',
            'err_rename': '重命名失败',

            'unknownreason': '可能是外星人篡改了代码...',
            'pcs_code': {
                3: "不支持此接口",
                4: "没有权限执行此操作",
                5: "IP未授权",
                110: "用户会话已过期，请重新登录",
                31001: "数据库查询错误",
                31002: "数据库连接错误",
                31003: "数据库返回空结果",
                31021: "网络错误",
                31022: "暂时无法连接服务器",
                31023: "输入参数错误",
                31024: "app id为空",
                31025: "后端存储错误",
                31041: "用户的cookie不是合法的百度cookie",
                31042: "用户未登陆",
                31043: "用户未激活",
                31044: "用户未授权",
                31045: "用户不存在",
                31046: "用户已经存在",
                31061: "文件已经存在",
                31062: "文件名非法",
                31063: "文件父目录不存在",
                31064: "无权访问此文件",
                31065: "目录已满",
                31066: "文件不存在",
                31067: "文件处理出错",
                31068: "文件创建失败",
                31069: "文件拷贝失败",
                31070: "文件删除失败",
                31071: "不能读取文件元信息",
                31072: "文件移动失败",
                31073: "文件重命名失败",
                31079: "未找到文件MD5，请使用上传API上传整个文件。",
                31081: "superfile创建失败",
                31082: "superfile 块列表为空",
                31083: "superfile 更新失败",
                31101: "tag系统内部错误",
                31102: "tag参数错误",
                31103: "tag系统错误",
                31110: "未授权设置此目录配额",
                31111: "配额管理只支持两级目录",
                31112: "超出配额",
                31113: "配额不能超出目录祖先的配额",
                31114: "配额不能比子目录配额小",
                31141: "请求缩略图服务失败",
                31201: "签名错误",
                31202: "文件不存在",
                31203: "设置acl失败",
                31204: "请求acl验证失败",
                31205: "获取acl失败",
                31206: "acl不存在",
                31207: "bucket已存在",
                31208: "用户请求错误",
                31209: "服务器错误",
                31210: "服务器不支持",
                31211: "禁止访问",
                31212: "服务不可用",
                31213: "重试出错",
                31214: "上传文件data失败",
                31215: "上传文件meta失败",
                31216: "下载文件data失败",
                31217: "下载文件meta失败",
                31218: "容量超出限额",
                31219: "请求数超出限额",
                31220: "流量超出限额",
                31298: "服务器返回值KEY非法",
                31299: "服务器返回值KEY不存在"
            }
        },
        'ui': {
            'shared_file_title': '[分享的] {0} (只读)',
            'load_share_for_edit': '正在加载分享的文件...',
            'share_sync_success': '分享内容已同步',
            'recycle_clear_confirm': '确认清空回收站么？清空后的文件无法恢复。',

            'fullscreen_exit_hint': '按 Esc 或 F11 退出全屏',

            'error_detail': '详细信息',
            'copy_and_feedback': '复制并反馈',
            'move_file_confirm': '确定把 "{0}" 移动到 "{1}" 吗？',
            'rename': '重命名',
            'rename_success': '{0} 重命名成功',
            'move_success': '{0} 移动成功到 {1}',

            'command': {
                'appendsiblingnode': '插入同级主题',
                'appendparentnode': '插入上级主题',
                'appendchildnode': '插入下级主题',
                'removenode': '删除',
                'editnode': '编辑',
                'arrangeup': '上移',
                'arrangedown': '下移',
                'resetlayout': '整理布局',
                'expandtoleaf': '展开全部节点',
                'expandtolevel1': '展开到一级节点',
                'expandtolevel2': '展开到二级节点',
                'expandtolevel3': '展开到三级节点',
                'expandtolevel4': '展开到四级节点',
                'expandtolevel5': '展开到五级节点',
                'expandtolevel6': '展开到六级节点',
                'fullscreen': '全屏',
                'outline': '大纲',
                'addtag': '添加'
            },

            'search': '搜索',

            'expandtoleaf': '展开',

            'back': '返回',

            'undo': '撤销 (Ctrl + Z)',
            'redo': '重做 (Ctrl + Y)',

            'tabs': {
                'idea': '思路',
                'appearence': '外观',
                'view': '视图'
            },

            'quickvisit': {
                'new': '新建 (Ctrl + Alt + N)',
                'save': '保存 (Ctrl + S)',
                'share': '分享 (Ctrl + Alt + S)',
                'feedback': '反馈问题（F1）',
                'editshare': '编辑'
            },

            'menu': {

                'mainmenutext': '百度脑图', // 主菜单按钮文本

                'newtab': '新建',
                'opentab': '打开',
                'savetab': '保存',
                'sharetab': '分享',
                'preferencetab': '设置',
                'helptab': '帮助',
                'feedbacktab': '反馈',
                'recenttab': '最近使用',
                'netdisktab': '百度云存储',
                'localtab': '本地文件',
                'drafttab': '草稿箱',
                'downloadtab': '导出到本地',
                'createsharetab': '当前脑图',
                'managesharetab': '已分享',

                'newheader': '新建脑图',
                'openheader': '打开',
                'saveheader': '保存到',
                'draftheader': '草稿箱',
                'shareheader': '分享我的脑图',
                'downloadheader': '导出到指定格式',
                'preferenceheader': '偏好设置',
                'helpheader': '帮助',
                'feedbackheader': '反馈'
            },

            'mydocument': '我的文档',
            'emptydir': '目录为空！',
            'pickfile': '选择文件...',
            'acceptfile': '支持的格式：{0}',
            'dropfile': '或将文件拖至此处',
            'unsupportedfile': '不支持的文件格式',
            'untitleddoc': '未命名文档',
            'overrideconfirm': '{0} 已存在，确认覆盖吗？',
            'checklogin': '检查登录状态中...',
            'loggingin': '正在登录...',
            'recent': '最近打开',
            'clearrecent': '清空',
            'clearrecentconfirm': '确认清空最近文档列表？',
            'cleardraft': '清空',
            'cleardraftconfirm': '确认清空草稿箱？',

            'none_share': '不分享',
            'public_share': '公开分享',
            'password_share': '私密分享',
            'email_share': '邮件邀请',
            'url_share': '脑图 URL 地址：',
            'sns_share': '社交网络分享：',
            'sns_share_text': '“{0}” - 我用百度脑图制作的思维导图，快看看吧！（地址：{1}）',
            'none_share_description': '不分享当前脑图',
            'public_share_description': '创建任何人可见的分享',
            'share_button_text': '创建',
            'password_share_description': '创建需要密码才可见的分享',
            'email_share_description': '创建指定人可见的分享，您还可以允许他们编辑',
            'ondev': '敬请期待！',
            'create_share_failed': '分享失败：{0}',
            'remove_share_failed': '删除失败：{1}',
            'copy': '复制',
            'copied': '已复制',
            'shared_tip': '当前脑图被 {0}  分享，你可以修改之后保存到自己的网盘上或再次分享',
            'current_share': '当前脑图',
            'manage_share': '我的分享',
            'share_remove_action': '不分享该脑图',
            'share_view_action': '打开分享地址',
            'share_edit_action': '编辑分享的文件',

            'login': '登录',
            'logout': '注销',
            'switchuser': '切换账户',
            'userinfo': '个人信息',
            'gotonetdisk': '我的网盘',
            'requirelogin': '请 <a class="login-button">登录</a> 后使用',
            'saveas': '保存为',
            'filename': '文件名',
            'fileformat': '保存格式',
            'save': '保存',
            'mkdir': '新建目录',
            'recycle': '回收站',
            'newdir': '未命名目录',

            'bold': '加粗',
            'italic': '斜体',
            'forecolor': '字体颜色',
            'fontfamily': '字体',
            'fontsize': '字号',
            'layoutstyle': '主题',
            'node': '节点操作',
            'saveto': '另存为',
            'hand': '允许拖拽',
            'camera': '定位根节点',
            'zoom-in': '放大（Ctrl+）',
            'zoom-out': '缩小（Ctrl-）',
            'markers': '标签',
            'resource': '资源',
            'help': '帮助',
            'preference': '偏好设置',
            'expandnode': '展开到叶子',
            'collapsenode': '收起到一级节点',
            'template': '模板',
            'theme': '皮肤',
            'clearstyle': '清除样式',
            'copystyle': '复制样式',
            'pastestyle': '粘贴样式',
            'appendsiblingnode': '同级主题',
            'appendchildnode': '下级主题',
            'arrangeup': '前调',
            'arrangedown': '后调',
            'editnode': '编辑',
            'removenode': '移除',
            'priority': '优先级',
            'removepriority': '移除优先级',
            'progress': {
                'p1': '未开始',
                'p2': '完成 1/8',
                'p3': '完成 1/4',
                'p4': '完成 3/8',
                'p5': '完成一半',
                'p6': '完成 5/8',
                'p7': '完成 3/4',
                'p8': '完成 7/8',
                'p9': '已完成',
                'p0': '清除进度'
            },
            'link': '链接',
            'image': '图片',
            'note': '备注',
            'insertlink': '插入链接',
            'insertimage': '插入图片',
            'insertnote': '插入备注',
            'removelink': '移除已有链接',
            'removeimage': '移除已有图片',
            'removenote': '移除已有备注',
            'resetlayout': '整理',

            'justnow': '刚刚',
            'minutesago': '{0} 分钟前',
            'hoursago': '{0} 小时前',
            'yesterday': '昨天',
            'daysago': '{0} 天前',
            'longago': '很久之前',

            'redirect': '您正在打开连接 {0}，百度脑图不能保证连接的安全性，是否要继续？',
            'navigator': '导航器',

            'unsavedcontent': '当前文件还没有保存到网盘：\n\n{0}\n\n虽然未保存的数据会缓存在草稿箱，但是清除浏览器缓存会导致草稿箱清除。',

            'shortcuts': '快捷键',
            'contact': '联系与反馈',
            'email': '邮件组',
            'qq_group': 'QQ 群',
            'github_issue': 'Github',
            'baidu_tieba': '贴吧',

            'clipboardunsupported': '您的浏览器不支持剪贴板，请使用快捷键复制',

            'load_success': '{0} 加载成功',
            'save_success': '{0} 已保存于 {1}',
            'autosave_success': '{0} 已自动保存于 {1}',

            'selectall': '全选',
            'selectrevert': '反选',
            'selectsiblings': '选择兄弟节点',
            'selectlevel': '选择同级节点',
            'selectpath': '选择路径',
            'selecttree': '选择子树'
        },
        'popupcolor': {
            'clearColor': '清空颜色',
            'standardColor': '标准颜色',
            'themeColor': '主题颜色'
        },
        'dialogs': {
            'markers': {
                'static': {
                    'lang_input_text': '文本内容：',
                    'lang_input_url': '链接地址：',
                    'lang_input_title': '标题：',
                    'lang_input_target': '是否在新窗口：'
                },
                'priority': '优先级',
                'none': '无',
                'progress': {
                    'title': '进度',
                    'notdone': '未完成',
                    'done1': '完成 1/8',
                    'done2': '完成 1/4',
                    'done3': '完成 3/8',
                    'done4': '完成 1/2',
                    'done5': '完成 5/8',
                    'done6': '完成 3/4',
                    'done7': '完成 7/8',
                    'done': '已完成'
                }
            },
            'help': {

            },
            'hyperlink': {},
            'image': {},
            'resource': {}
        },
        'hyperlink': {
            'hyperlink': '链接...',
            'unhyperlink': '移除链接'
        },
        'image': {
            'image': '图片...',
            'removeimage': '移除图片'
        },
        'marker': {
            'marker': '进度/优先级...'
        },
        'resource': {
            'resource': '资源...'
        }
    },
    'jp':{
        "template": {
          "default": "マインドマッピング",
          "tianpan": "スカイチャート",
          "structure": "組織図",
          "filetree": "ディレクトリ組織図",
          "right": "論理構造図",
          "fish-bone": "特性要因図"
        },
        "hotbox": {
          "undo": "取り消す",
          "redo": "やり直す",
          "appendsiblingnode": "同じレベルで",
          "appendparentnode": "上長",
          "appendchildnode": "下位",
          "editnode": "編集",
          "arrangeup": "上に移動",
          "arrangedown": "下に移動",
          "resetlayout": "レイアウトを整理する",
          "remove": "消去",
          "priority": "優先順位",
          "progress": "スケジュール",
          "importnode": "インポート ノード",
          "exportnode": "ノードのエクスポート"
        },
        "theme": {
          "classic": "ブレイン マップ クラシック",
          "classic-compact": "コンパクト クラシック",
          "snow": "優しい冷たい光",
          "snow-compact": "コンパクト冷光",
          "fish": "特性要因図",
          "wire": "ワイヤーフレーム",
          "fresh-red": "フレッシュレッド",
          "fresh-soil": "アースイエロー",
          "fresh-green": "文芸緑",
          "fresh-blue": "空色",
          "fresh-purple": "ロマンティックパープル",
          "fresh-pink": "ブレインパウダー",
          "fresh-red-compat": "コンパクトレッド",
          "fresh-soil-compat": "コンパクトイエロー",
          "fresh-green-compat": "コンパクトグリーン",
          "fresh-blue-compat": "コンパクトブルー",
          "fresh-purple-compat": "コンパクトパープル",
          "fresh-pink-compat": "コンパクトパウダー",
          "tianpan": "クラシックディッシュ",
          "tianpan-compact": "コンパクトディッシュ"
        },
        "maintopic": "中心テーマ",
        "topic": "ブランチ トピック",
        "panels": {
          "history": "歴史",
          "template": "レンプレート",
          "theme": "肌",
          "layout": "レイアウト",
          "style": "スタイル",
          "font": "言葉",
          "color": "色",
          "background": "バックグラウンド",
          "insert": "入れる",
          "arrange": "調整",
          "nodeop": "現在",
          "priority": "優先順位",
          "progress": "スケジュール",
          "resource": "リソース",
          "note": "述べる",
          "attachment": "付録",
          "word": "言葉"
        },
        "error_message": {
          "title": "おっと、マインドマップが間違っていました",
          "err_load": "マインドマップの読み込みに失敗しました",
          "err_save": "マインドマップを保存できませんでした",
          "err_network": "ネットワークエラー",
          "err_doc_resolve": "ドキュメントの解析に失敗しました",
          "err_unknown": "何か奇妙なことが起こった",
          "err_localfile_read": "ファイル読み込みエラー",
          "err_download": "ファイルのダウンロードに失敗しました",
          "err_remove_share": "共有を解除できませんでした",
          "err_create_share": "共有に失敗しました",
          "err_mkdir": "ディレクトリの作成に失敗しました",
          "err_ls": "ディレクトリの読み取りに失敗しました",
          "err_share_data": "共有コンテンツの読み込み中にエラーが発生しました",
          "err_share_sync_fail": "共有コンテンツの同期に失敗しました",
          "err_move_file": "ファイルの移動に失敗しました",
          "err_rename": "名前を変更できませんでした",
          "unknownreason": "エイリアンがコードを改ざんしたのかもしれません...",
          "pcs_code": {
            "3": "このインターフェースはサポートされていません",
            "4": "この操作を実行する権限がありません",
            "5": "IP が許可されていません",
            "110": "ユーザー セッションの有効期限が切れました。再度ログインしてください",
            "31001": "データベース クエリ エラー",
            "31002": "データベース接続エラー",
            "31003": "データベースは空の結果を返します",
            "31021": "ネットワークエラー",
            "31022": "サーバーに一時的に接続できません",
            "31023": "間違った入力パラメータ",
            "31024": "アプリ ID が空です",
            "31025": "バックエンド ストレージ エラー",
            "31041": "ユーザーの Cookie は正規のバイドゥ Cookie ではありません",
            "31042": "ユーザーがログインしていません",
            "31043": "ユーザーはアクティブではありません",
            "31044": "ユーザーは許可されていません",
            "31045": "ユーザーは存在しません",
            "31046": "このユーザーは既に存在します",
            "31061": "ファイルは既に存在します",
            "31062": "不正なファイル名",
            "31063": "ファイルの親ディレクトリが存在しません",
            "31064": "このファイルにアクセスする権限がありません",
            "31065": "ディレクトリがいっぱいです",
            "31066": "ファイルが存在しません",
            "31067": "ファイル処理エラー",
            "31068": "ファイルの作成に失敗しました",
            "31069": "ファイルのコピーに失敗しました",
            "31070": "ファイルの削除に失敗しました",
            "31071": "ファイルのメタ情報を読み取れませんでした",
            "31072": "ファイルの移動に失敗しました",
            "31073": "ファイルの名前変更に失敗しました",
            "31079": "ファイル MD5 が見つかりません。アップロード API を使用してファイル全体をアップロードしてください。",
            "31081": "スーパーファイルの作成に失敗しました",
            "31082": "スーパーファイルのブロック リストが空です",
            "31083": "スーパーファイルの更新に失敗しました",
            "31101": "タグ システムの内部エラー",
            "31102": "タグ パラメータ エラー",
            "31103": "タグシステムエラー",
            "31110": "このディレクトリのクォータを設定する権限がありません",
            "31111": "クォータ管理は 2 レベルのディレクトリのみをサポートします",
            "31112": "割り当て超過",
            "31113": "クォータは、ディレクトリの祖先のクォータを超えることはできません",
            "31114": "サブディレクトリのクォータよりもクォータを小さくすることはできません",
            "31141": "サムネイル サービスのリクエストに失敗しました",
            "31201": "署名エラー",
            "31202": "ファイルが存在しません",
            "31203": "ACL の設定に失敗しました",
            "31204": "ACL 検証のリクエストに失敗しました",
            "31205": "ACL の取得に失敗しました",
            "31206": "acl が存在しません",
            "31207": "バケットはすでに存在します",
            "31208": "ユーザーリクエストエラー",
            "31209": "サーバーエラー",
            "31210": "サーバーはサポートしていません",
            "31211": "アクセスなし",
            "31212": "サービスは利用できません",
            "31213": "エラー時に再試行",
            "31214": "ファイルデータのアップロードに失敗しました",
            "31215": "ファイル メタのアップロードに失敗しました",
            "31216": "ファイルデータのダウンロードに失敗しました",
            "31217": "ファイル メタのダウンロードに失敗しました",
            "31218": "容量超過",
            "31219": "リクエスト数が上限を超えています",
            "31220": "トラフィック制限を超えました",
            "31298": "サーバーが無効なキーを返しました",
            "31299": "サーバーの戻り値 KEY が存在しません"
          }
        },
        "ui": {
          "shared_file_title": "[共有] {0} (読み取り専用)",
          "load_share_for_edit": "共有ファイルを読み込んでいます...",
          "share_sync_success": "共有コンテンツが同期されました",
          "recycle_clear_confirm": "ごみ箱を空にしてよろしいですか?",
          "fullscreen_exit_hint": "全画面表示を終了するには、Esc または F11 を押します",
          "error_detail": "詳細",
          "copy_and_feedback": "コピーとフィードバック",
          "move_file_confirm": "\"{0}\" を \"{1}\" に移動してもよろしいですか?",
          "rename": "名前を変更",
          "rename_success": "{0} の名前が正常に変更されました",
          "move_success": "{0} が {1} に正常に移動しました",
          "command": {
            "appendsiblingnode": "兄弟トピックを挿入",
            "appendparentnode": "親トピックを挿入",
            "appendchildnode": "下位トピックを挿入",
            "removenode": "消去",
            "editnode": "編集",
            "arrangeup": "上に移動",
            "arrangedown": "下に移動",
            "resetlayout": "レイアウトを整理する",
            "expandtoleaf": "すべてのノードを展開",
            "expandtolevel1": "レベル 1 のノードに展開",
            "expandtolevel2": "セカンダリ ノードに展開する",
            "expandtolevel3": "第 3 レベルのノードに展開する",
            "expandtolevel4": "4 レベルのノードに展開",
            "expandtolevel5": "5 レベルのノードに展開",
            "expandtolevel6": "6 レベルのノードに展開",
            "fullscreen": "全画面表示",
            "outline": "概要",
            "addtag": "追加"
          },
          "search": "検索",
          "expandtoleaf": "拡大",
          "back": "戻る",
          "undo": "元に戻す (Ctrl + Z)",
          "redo": "やり直し (Ctrl + Y)",
          "tabs": {
            "idea": "一連の考え",
            "appearence": "外観",
            "view": "意見"
          },
          "quickvisit": {
            "new": "新規 (Ctrl + Alt + N)",
            "save": "保存 (Ctrl + S)",
            "share": "共有 (Ctrl + Alt + S)",
            "feedback": "フィードバックの質問 (F1)",
            "editshare": "編集"
          },
          "menu": {
            "mainmenutext": "百度脳地図",
            "newtab": "新築",
            "opentab": "開ける",
            "savetab": "保存",
            "sharetab": "共有",
            "preferencetab": "設定",
            "helptab": "ヘルプ",
            "feedbacktab": "フィードバック",
            "recenttab": "最近使用された",
            "netdisktab": "バイドゥ クラウド ストレージ",
            "localtab": "ローカル ファイル",
            "drafttab": "ドラフトボックス",
            "downloadtab": "ローカルにエクスポート",
            "createsharetab": "現在のマインドマップ",
            "managesharetab": "共有",
            "newheader": "新しいマインド マップを作成する",
            "openheader": "開ける",
            "saveheader": "に保存",
            "draftheader": "ドラフトボックス",
            "shareheader": "私のマインドマップを共有する",
            "downloadheader": "指定した形式にエクスポート",
            "preferenceheader": "環境設定",
            "helpheader": "ヘルプ",
            "feedbackheader": "フィードバック"
          },
          "mydocument": "私の文書",
          "emptydir": "ディレクトリが空です!",
          "pickfile": "ドキュメントを選択...",
          "acceptfile": "サポートされている形式: {0}",
          "dropfile": "またはここにファイルをドラッグします",
          "unsupportedfile": "サポートされていないファイル形式",
          "untitleddoc": "無題のドキュメント",
          "overrideconfirm": "{0} は既に存在します。上書きしてもよろしいですか?",
          "checklogin": "ログイン状態を確認しています...",
          "loggingin": "ログイン中...",
          "recent": "最近開いた",
          "clearrecent": "空",
          "clearrecentconfirm": "最近使用したドキュメントのリストをクリアしてもよろしいですか?",
          "cleardraft": "空",
          "cleardraftconfirm": "下書きボックスをクリアしてもよろしいですか？",
          "none_share": "共有しない",
          "public_share": "公に共有する",
          "password_share": "プライベート共有",
          "email_share": "招待メール",
          "url_share": "マインド マップの URL アドレス:",
          "sns_share": "ソーシャル ネットワークで共有する:",
          "sns_share_text": "\"{0}\" - Baidu Brain Map で作成したマインド マップをご覧ください。 ",
          "none_share_description": "現在のマインド マップを共有しない",
          "public_share_description": "誰にでも見える共有を作成する",
          "share_button_text": "作成",
          "password_share_description": "表示にパスワードが必要な共有を作成する",
          "email_share_description": "特定のユーザーに表示される共有を作成し、編集を許可することもできます",
          "ondev": "乞うご期待！",
          "create_share_failed": "共有に失敗しました: {0}",
          "remove_share_failed": "削除に失敗しました: {1}",
          "copy": "コピー",
          "copied": "コピーした",
          "shared_tip": "現在のマインド マップは {0} によって共有されています。変更して自分のネットワーク ディスクに保存するか、再度共有することができます",
          "current_share": "現在のマインドマップ",
          "manage_share": "私の分け前",
          "share_remove_action": "このマインドマップを共有しないでください",
          "share_view_action": "共有アドレスを開く",
          "share_edit_action": "共有ファイルの編集",
          "login": "ログイン",
          "logout": "ログアウト",
          "switchuser": "アカウントを切り替える",
          "userinfo": "個人情報",
          "gotonetdisk": "私のネットワークディスク",
          "requirelogin": "使用するには<a class=\"login-button\">ログイン</a>してください",
          "saveas": "名前を付けて保存",
          "filename": "ファイル名",
          "fileformat": "保存形式",
          "save": "保存",
          "mkdir": "新しいディレクトリ",
          "recycle": "ごみ箱",
          "newdir": "名前のないディレクトリ",
          "bold": "大胆な",
          "italic": "斜体",
          "forecolor": "フォントの色",
          "fontfamily": "フォント",
          "fontsize": "フォントサイズ",
          "layoutstyle": "テーマ",
          "node": "ノード操作",
          "saveto": "名前を付けて保存",
          "hand": "ドラッグを許可",
          "camera": "ルートノードを見つける",
          "zoom-in": "ズームイン (Ctrl+)",
          "zoom-out": "ズームアウト (Ctrl-)",
          "markers": "ラベル",
          "resource": "リソース",
          "help": "ヘルプ",
          "preference": "環境設定",
          "expandnode": "葉っぱに広げます",
          "collapsenode": "第 1 レベルのノードに折りたたむ",
          "template": "レンプレート",
          "theme": "肌",
          "clearstyle": "クリアスタイル",
          "copystyle": "コピースタイル",
          "pastestyle": "貼り付けスタイル",
          "appendsiblingnode": "兄弟トピック",
          "appendchildnode": "下位トピック",
          "arrangeup": "トップノート",
          "arrangedown": "アフタートーン",
          "editnode": "編集",
          "removenode": "削除",
          "priority": "優先順位",
          "removepriority": "優先順位を削除",
          "progress": {
            "p1": "開始していません",
            "p2": "1/8完了",
            "p3": "1/4完了",
            "p4": "3/8完了",
            "p5": "半分終わった",
            "p6": "5/8 完了",
            "p7": "3/4完了",
            "p8": "7/8 完了",
            "p9": "完了",
            "p0": "明確な進捗"
          },
          "link": "リンク",
          "image": "写真",
          "note": "述べる",
          "insertlink": "リンクを挿入",
          "insertimage": "画像を挿入",
          "insertnote": "メモを挿入",
          "removelink": "既存のリンクを削除",
          "removeimage": "既存の画像を削除",
          "removenote": "既存のメモを削除",
          "resetlayout": "几帳面",
          "justnow": "ただ",
          "minutesago": "{0}分前",
          "hoursago": "{0}時間前",
          "yesterday": "昨日",
          "daysago": "{0}日前",
          "longago": "昔々",
          "redirect": "接続 {0} を開いています。Baidu Brain Map は接続のセキュリティを保証できません。続行しますか?",
          "navigator": "ナビゲーター",
          "unsavedcontent": "現在のファイルはネットワーク ディスクに保存されていません:\n\n",
          "shortcuts": "ホットキー",
          "contact": "連絡先とフィードバック",
          "email": "メールグループ",
          "qq_group": "QQグループ",
          "github_issue": "ギットハブ",
          "baidu_tieba": "ポストバー",
          "clipboardunsupported": "お使いのブラウザはクリップボードをサポートしていません。ショートカット キーを使用してコピーしてください",
          "load_success": "{0} が正常にロードされました",
          "save_success": "{0} は {1} に保存されました",
          "autosave_success": "{0} は {1} に自動的に保存されました",
          "selectall": "すべて選択",
          "selectrevert": "逆選挙",
          "selectsiblings": "兄弟ノードを選択",
          "selectlevel": "兄弟ノードを選択",
          "selectpath": "道を選ぶ",
          "selecttree": "サブツリーを選択"
        },
        "popupcolor": {
          "clearColor": "クリアカラー",
          "standardColor": "標準色",
          "themeColor": "テーマカラー"
        },
        "dialogs": {
          "markers": {
            "static": {
              "lang_input_text": "テキストの内容:",
              "lang_input_url": "リンクアドレス:",
              "lang_input_title": "タイトル：",
              "lang_input_target": "新しいウィンドウかどうか:"
            },
            "priority": "優先順位",
            "none": "なし",
            "progress": {
              "title": "スケジュール",
              "notdone": "元に戻す",
              "done1": "1/8完了",
              "done2": "1/4完了",
              "done3": "3/8完了",
              "done4": "1/2完了",
              "done5": "5/8 完了",
              "done6": "3/4完了",
              "done7": "7/8 完了",
              "done": "完了"
            }
          },
          "help": {},
          "hyperlink": {},
          "image": {},
          "resource": {}
        },
        "hyperlink": {
          "hyperlink": "リンク...",
          "unhyperlink": "リンクを削除"
        },
        "image": {
          "image": "写真...",
          "removeimage": "画像を削除"
        },
        "marker": {
          "marker": "進行状況/優先度..."
        },
        "resource": {
          "resource": "リソース..."
        }
    },
    'ko':{
        "template": {
          "default": "마인드 매핑",
          "tianpan": "스카이 차트",
          "structure": "조직도",
          "filetree": "디렉토리 조직도",
          "right": "논리적 구조 다이어그램",
          "fish-bone": "피쉬본 다이어그램"
        },
        "hotbox": {
          "undo": "취소",
          "redo": "다시 하다",
          "appendsiblingnode": "같은 수준에서",
          "appendparentnode": "우수한",
          "appendchildnode": "부하",
          "editnode": "편집하다",
          "arrangeup": "이동",
          "arrangedown": "아래로 이동",
          "resetlayout": "레이아웃 구성",
          "remove": "삭제",
          "priority": "우선 사항",
          "progress": "일정",
          "importnode": "가져오기 노드",
          "exportnode": "내보내기 노드"
        },
        "theme": {
          "classic": "브레인 맵 클래식",
          "classic-compact": "컴팩트 클래식",
          "snow": "부드러운 차가운 빛",
          "snow-compact": "소형 콜드 라이트",
          "fish": "피쉬본 다이어그램",
          "wire": "와이어프레임",
          "fresh-red": "신선한 빨강",
          "fresh-soil": "지구 황색",
          "fresh-green": "문학적 녹색",
          "fresh-blue": "하늘색",
          "fresh-purple": "로맨틱 퍼플",
          "fresh-pink": "브레인파우더",
          "fresh-red-compat": "컴팩트 레드",
          "fresh-soil-compat": "콤팩트 옐로우",
          "fresh-green-compat": "콤팩트 그린",
          "fresh-blue-compat": "컴팩트 블루",
          "fresh-purple-compat": "컴팩트 퍼플",
          "fresh-pink-compat": "컴팩트 파우더",
          "tianpan": "클래식 요리",
          "tianpan-compact": "콤팩트 접시"
        },
        "maintopic": "중심 주제",
        "topic": "분기 주제",
        "panels": {
          "history": "역사",
          "template": "주형",
          "theme": "피부",
          "layout": "공들여 나열한 것",
          "style": "스타일",
          "font": "단어",
          "color": "색상",
          "background": "배경",
          "insert": "끼워 넣다",
          "arrange": "조정",
          "nodeop": "현재의",
          "priority": "우선 사항",
          "progress": "일정",
          "resource": "자원",
          "note": "주목",
          "attachment": "부록",
          "word": "단어"
        },
        "error_message": {
          "title": "앗 마인드맵이 잘못됐네요",
          "err_load": "마인드맵 불러오기 실패",
          "err_save": "마인드맵 저장 실패",
          "err_network": "네트워크 오류",
          "err_doc_resolve": "문서 파싱 실패",
          "err_unknown": "이상한 일이 일어났다",
          "err_localfile_read": "파일 읽기 오류",
          "err_download": "파일 다운로드 실패",
          "err_remove_share": "공유 취소 실패",
          "err_create_share": "공유 실패",
          "err_mkdir": "디렉토리 생성 실패",
          "err_ls": "디렉터리를 읽지 못했습니다.",
          "err_share_data": "공유 콘텐츠를 로드하는 중에 오류가 발생했습니다.",
          "err_share_sync_fail": "공유 콘텐츠 동기화 실패",
          "err_move_file": "파일 이동 실패",
          "err_rename": "이름 바꾸기 실패",
          "unknownreason": "외계인이 암호를 조작했을 수도 있습니다...",
          "pcs_code": {
            "3": "이 인터페이스는 지원되지 않습니다",
            "4": "이 작업을 수행할 수 있는 권한이 없습니다.",
            "5": "IP가 승인되지 않음",
            "110": "사용자 세션이 만료되었습니다. 다시 로그인하십시오.",
            "31001": "데이터베이스 쿼리 오류",
            "31002": "데이터베이스 연결 오류",
            "31003": "데이터베이스가 빈 결과를 반환합니다.",
            "31021": "네트워크 오류",
            "31022": "일시적으로 서버에 연결할 수 없습니다.",
            "31023": "잘못된 입력 매개변수",
            "31024": "앱 ID가 비어 있습니다.",
            "31025": "백엔드 스토리지 오류",
            "31041": "사용자의 쿠키는 합법적인 Baidu 쿠키가 아닙니다.",
            "31042": "로그인하지 않은 사용자",
            "31043": "사용자가 활성 상태가 아닙니다.",
            "31044": "사용자가 승인되지 않았습니다.",
            "31045": "사용자가 존재하지 않습니다",
            "31046": "사용자가 이미 존재합니다",
            "31061": "파일이 이미 존재합니다.",
            "31062": "불법 파일 이름",
            "31063": "파일의 상위 디렉토리가 존재하지 않습니다",
            "31064": "이 파일에 액세스할 수 있는 권한이 없습니다",
            "31065": "디렉토리 가득 참",
            "31066": "파일이 없습니다",
            "31067": "파일 처리 오류",
            "31068": "파일 생성 실패",
            "31069": "파일 복사 실패",
            "31070": "파일 삭제 실패",
            "31071": "파일 메타 정보를 읽을 수 없습니다.",
            "31072": "파일 이동 실패",
            "31073": "파일 이름 바꾸기 실패",
            "31079": "파일 MD5를 찾을 수 없습니다. 업로드 API를 사용하여 전체 파일을 업로드하십시오.",
            "31081": "슈퍼파일 생성 실패",
            "31082": "슈퍼파일 차단 목록이 비어 있습니다.",
            "31083": "슈퍼파일 업데이트 실패",
            "31101": "태그 시스템 내부 오류",
            "31102": "태그 매개변수 오류",
            "31103": "태그 시스템 오류",
            "31110": "이 디렉터리에 대한 할당량을 설정할 권한이 없습니다.",
            "31111": "할당량 관리는 2단계 디렉터리만 지원합니다.",
            "31112": "할당량 초과",
            "31113": "할당량은 디렉터리 상위 할당량을 초과할 수 없습니다.",
            "31114": "할당량은 하위 디렉터리 할당량보다 작을 수 없습니다.",
            "31141": "썸네일 서비스 요청 실패",
            "31201": "서명 오류",
            "31202": "파일이 없습니다",
            "31203": "ACL을 설정하지 못했습니다.",
            "31204": "ACL 확인 요청 실패",
            "31205": "ACL을 가져오지 못했습니다.",
            "31206": ".acl이 존재하지 않습니다",
            "31207": "버킷이 이미 존재합니다.",
            "31208": "사용자 요청 오류",
            "31209": "서버 오류",
            "31210": "서버가 지원하지 않습니다",
            "31211": "접근 금지",
            "31212": "서비스를 이용할 수 없습니다",
            "31213": "오류 시 재시도",
            "31214": "파일 데이터를 업로드하지 못했습니다.",
            "31215": "파일 메타를 업로드하지 못했습니다.",
            "31216": "파일 데이터를 다운로드하지 못했습니다.",
            "31217": "파일 메타를 다운로드하지 못했습니다.",
            "31218": "용량 초과",
            "31219": "요청 수가 한도를 초과합니다.",
            "31220": "트래픽 한도 초과",
            "31298": "서버가 잘못된 키를 반환합니다.",
            "31299": "서버에서 반환한 값 KEY가 존재하지 않습니다."
          }
        },
        "ui": {
          "shared_file_title": "[공유됨] {0}(읽기 전용)",
          "load_share_for_edit": "공유 파일 로드 중...",
          "share_sync_success": "공유 콘텐츠가 동기화되었습니다.",
          "recycle_clear_confirm": "휴지통을 비우시겠습니까? ",
          "fullscreen_exit_hint": "전체 화면을 종료하려면 Esc 또는 F11을 누르십시오.",
          "error_detail": "세부",
          "copy_and_feedback": "복사 및 피드백",
          "move_file_confirm": "\"{0}\"을(를) \"{1}\"(으)로 이동하시겠습니까?",
          "rename": "이름 바꾸기",
          "rename_success": "{0}의 이름이 성공적으로 변경되었습니다.",
          "move_success": "{0}이(가) {1}(으)로 성공적으로 이동했습니다.",
          "command": {
            "appendsiblingnode": "형제 주제 삽입",
            "appendparentnode": "상위 주제 삽입",
            "appendchildnode": "종속 항목 삽입",
            "removenode": "삭제",
            "editnode": "편집하다",
            "arrangeup": "이동",
            "arrangedown": "아래로 이동",
            "resetlayout": "레이아웃 구성",
            "expandtoleaf": "모든 노드 확장",
            "expandtolevel1": "레벨 1 노드로 확장",
            "expandtolevel2": "보조 노드로 확장",
            "expandtolevel3": "3단계 노드로 확장",
            "expandtolevel4": "4단계 노드로 확장",
            "expandtolevel5": "5단계 노드로 확장",
            "expandtolevel6": "6레벨 노드로 확장",
            "fullscreen": "전체 화면",
            "outline": "개요",
            "addtag": "에 추가"
          },
          "search": "찾다",
          "expandtoleaf": "확장하다",
          "back": "반품",
          "undo": "실행 취소(Ctrl + Z)",
          "redo": "다시 실행(Ctrl + Y)",
          "tabs": {
            "idea": "생각의 기차",
            "appearence": "외부",
            "view": "보다"
          },
          "quickvisit": {
            "new": "새로 만들기(Ctrl + Alt + N)",
            "save": "저장(Ctrl + S)",
            "share": "공유(Ctrl + Alt + S)",
            "feedback": "피드백 질문(F1)",
            "editshare": "편집하다"
          },
          "menu": {
            "mainmenutext": "Baidu 뇌 지도",
            "newtab": "새 빌드",
            "opentab": "열려 있는",
            "savetab": "구하다",
            "sharetab": "공유하다",
            "preferencetab": "설정",
            "helptab": "돕다",
            "feedbacktab": "피드백",
            "recenttab": "최근 사용",
            "netdisktab": "바이두 클라우드 스토리지",
            "localtab": "로컬 파일",
            "drafttab": "드래프트 박스",
            "downloadtab": "로컬로 내보내기",
            "createsharetab": "현재 마인드맵",
            "managesharetab": "공유",
            "newheader": "새로운 마인드맵 만들기",
            "openheader": "열려 있는",
            "saveheader": "저장 위치",
            "draftheader": "드래프트 박스",
            "shareheader": "내 마인드맵 공유하기",
            "downloadheader": "지정된 형식으로 내보내기",
            "preferenceheader": "기본 설정",
            "helpheader": "돕다",
            "feedbackheader": "피드백"
          },
          "mydocument": "내 문서",
          "emptydir": "디렉토리가 비어 있습니다!",
          "pickfile": "문서 선택...",
          "acceptfile": "지원되는 형식: {0}",
          "dropfile": "또는 여기로 파일 드래그",
          "unsupportedfile": "지원되지 않는 파일 형식",
          "untitleddoc": "제목 없는 문서",
          "overrideconfirm": "{0}이(가) 이미 존재합니다. 덮어쓰시겠습니까?",
          "checklogin": "로그인 상태 확인 중...",
          "loggingin": "로그인...",
          "recent": "최근에 열었습니다",
          "clearrecent": "비어 있는",
          "clearrecentconfirm": "최근 문서 목록을 지우시겠습니까?",
          "cleardraft": "비어 있는",
          "cleardraftconfirm": "드래프트 박스를 비우시겠습니까?",
          "none_share": "공유하지 마십시오",
          "public_share": "공개적으로 공유",
          "password_share": "비공개 공유",
          "email_share": "이메일 초대장",
          "url_share": "마인드맵 URL 주소:",
          "sns_share": "소셜 네트워크에서 공유:",
          "sns_share_text": "\"{0}\" - Baidu Brain Map으로 만든 마인드맵, 한번 보세요! ",
          "none_share_description": "현재 마인드맵 공유하지 않기",
          "public_share_description": "누구나 볼 수 있는 공유 만들기",
          "share_button_text": "만들다",
          "password_share_description": "암호를 표시해야 하는 공유 만들기",
          "email_share_description": "지정된 사람들이 볼 수 있는 공유를 생성하고 그들이 편집하도록 허용할 수도 있습니다.",
          "ondev": "계속 지켜봐!",
          "create_share_failed": "공유 실패: {0}",
          "remove_share_failed": "삭제 실패: {1}",
          "copy": "복사",
          "copied": "복사",
          "shared_tip": "현재 마인드맵은 {0}님이 공유하고 있습니다. 수정하여 자신의 네트워크 디스크에 저장하거나 다시 공유할 수 있습니다.",
          "current_share": "현재 마인드맵",
          "manage_share": "내 몫",
          "share_remove_action": "이 마인드 맵을 공유하지 마십시오",
          "share_view_action": "공유 주소 열기",
          "share_edit_action": "공유 파일 수정",
          "login": "로그인",
          "logout": "로그 아웃",
          "switchuser": "계정 전환",
          "userinfo": "개인 정보",
          "gotonetdisk": "내 네트워크 디스크",
          "requirelogin": "사용하려면 <a class=\"login-button\">로그인</a>하세요.",
          "saveas": "다른 이름으로 저장",
          "filename": "파일 이름",
          "fileformat": "저장 형식",
          "save": "구하다",
          "mkdir": "새 디렉토리",
          "recycle": "쓰레기통",
          "newdir": "이름 없는 디렉토리",
          "bold": "용감한",
          "italic": "이탤릭체",
          "forecolor": "글꼴 색상",
          "fontfamily": "폰트",
          "fontsize": "글꼴 크기",
          "layoutstyle": "주제",
          "node": "노드 운영",
          "saveto": "다른 이름으로 저장",
          "hand": "끌기 허용",
          "camera": "루트 노드를 찾습니다",
          "zoom-in": "확대(Ctrl+)",
          "zoom-out": "축소(Ctrl-)",
          "markers": "상표",
          "resource": "자원",
          "help": "돕다",
          "preference": "기본 설정",
          "expandnode": "잎사귀까지 번지다",
          "collapsenode": "첫 번째 수준 노드로 접기",
          "template": "주형",
          "theme": "피부",
          "clearstyle": "클리어 스타일",
          "copystyle": "복사 스타일",
          "pastestyle": "붙여넣기 스타일",
          "appendsiblingnode": "형제 주제",
          "appendchildnode": "종속 주제",
          "arrangeup": "탑 노트",
          "arrangedown": "애프터 톤",
          "editnode": "편집하다",
          "removenode": "제거하다",
          "priority": "우선 사항",
          "removepriority": "우선 순위 제거",
          "progress": {
            "p1": "시작하지 않았습니다",
            "p2": "1/8 완료",
            "p3": "1/4 완료",
            "p4": "3/8 완료",
            "p5": "절반 완료",
            "p6": "완료 5/8",
            "p7": "3/4 완료",
            "p8": "7/8 완료",
            "p9": "완전한",
            "p0": "명확한 진행"
          },
          "link": "링크",
          "image": "그림",
          "note": "주목",
          "insertlink": "링크 삽입",
          "insertimage": "그림 삽입",
          "insertnote": "메모 삽입",
          "removelink": "기존 링크 제거",
          "removeimage": "기존 이미지 제거",
          "removenote": "기존 메모 제거",
          "resetlayout": "정돈하다",
          "justnow": "단지",
          "minutesago": "{0}분 전",
          "hoursago": "{0}시간 전",
          "yesterday": "어제",
          "daysago": "{0}일 전",
          "longago": "옛날에",
          "redirect": "연결 {0}을(를) 여는 중입니다. Baidu Brain Map에서 연결의 보안을 보장할 수 없습니다. 계속하시겠습니까?",
          "navigator": "항해자",
          "unsavedcontent": "현재 파일이 네트워크 디스크에 저장되지 않았습니다.\n\n",
          "shortcuts": "단축키",
          "contact": "연락 및 피드백",
          "email": "메일 그룹",
          "qq_group": "QQ 그룹",
          "github_issue": "Github",
          "baidu_tieba": "포스트 바",
          "clipboardunsupported": "브라우저가 클립보드를 지원하지 않습니다. 단축키를 사용하여 복사하세요.",
          "load_success": "{0} 로드 완료",
          "save_success": "{0}이(가) {1}에 저장되었습니다.",
          "autosave_success": "{0}이(가) {1}에 자동으로 저장되었습니다.",
          "selectall": "모두 선택",
          "selectrevert": "역선거",
          "selectsiblings": "형제 노드 선택",
          "selectlevel": "형제 노드 선택",
          "selectpath": "경로를 선택",
          "selecttree": "하위 트리 선택"
        },
        "popupcolor": {
          "clearColor": "선명한 색상",
          "standardColor": "표준 색상",
          "themeColor": "테마 색상"
        },
        "dialogs": {
          "markers": {
            "static": {
              "lang_input_text": "텍스트 내용:",
              "lang_input_url": "링크 주소:",
              "lang_input_title": "제목:",
              "lang_input_target": "새 창에서 여부:"
            },
            "priority": "우선 사항",
            "none": "없음",
            "progress": {
              "title": "일정",
              "notdone": "푼",
              "done1": "1/8 완료",
              "done2": "1/4 완료",
              "done3": "3/8 완료",
              "done4": "1/2 완료",
              "done5": "완료 5/8",
              "done6": "3/4 완료",
              "done7": "7/8 완료",
              "done": "완전한"
            }
          },
          "help": {},
          "hyperlink": {},
          "image": {},
          "resource": {}
        },
        "hyperlink": {
          "hyperlink": "링크...",
          "unhyperlink": "링크 제거"
        },
        "image": {
          "image": "그림...",
          "removeimage": "이미지 제거"
        },
        "marker": {
          "marker": "진행/우선순위..."
        },
        "resource": {
          "resource": "자원..."
        }
    },
    'pl':{
        "template": {
          "default": "mapowanie myśli",
          "tianpan": "wykres nieba",
          "structure": "Schemat organizacyjny",
          "filetree": "Schemat organizacyjny katalogu",
          "right": "Diagram struktury logicznej",
          "fish-bone": "schemat rybiej ości"
        },
        "hotbox": {
          "undo": "unieważnić",
          "redo": "przerobić",
          "appendsiblingnode": "na tym samym poziomie",
          "appendparentnode": "znakomity",
          "appendchildnode": "podrzędny",
          "editnode": "edytować",
          "arrangeup": "Podnieść",
          "arrangedown": "padnij",
          "resetlayout": "Zorganizuj układ",
          "remove": "usuwać",
          "priority": "priorytet",
          "progress": "harmonogram",
          "importnode": "węzeł importu",
          "exportnode": "węzeł eksportu"
        },
        "theme": {
          "classic": "Klasyczna mapa mózgu",
          "classic-compact": "kompaktowa klasyka",
          "snow": "Delikatne zimne światło",
          "snow-compact": "Kompaktowe zimne światło",
          "fish": "Diagram Fishbone",
          "wire": "szkielet",
          "fresh-red": "świeża czerwień",
          "fresh-soil": "ziemisty żółty",
          "fresh-green": "Literacka zieleń",
          "fresh-blue": "niebieskie niebo",
          "fresh-purple": "romantyczny fiolet",
          "fresh-pink": "Proszek mózgowy",
          "fresh-red-compat": "kompaktowa czerwień",
          "fresh-soil-compat": "zwarty żółty",
          "fresh-green-compat": "kompaktowa zieleń",
          "fresh-blue-compat": "kompaktowy niebieski",
          "fresh-purple-compat": "zwarty fioletowy",
          "fresh-pink-compat": "puder w kompakcie",
          "tianpan": "Klasyczne danie",
          "tianpan-compact": "Kompaktowe danie"
        },
        "maintopic": "motyw przewodni",
        "topic": "temat oddziału",
        "panels": {
          "history": "historia",
          "template": "szablon",
          "theme": "skóra",
          "layout": "układ",
          "style": "styl",
          "font": "Słowo",
          "color": "kolor",
          "background": "tło",
          "insert": "wstawić",
          "arrange": "Modyfikacja",
          "nodeop": "aktualny",
          "priority": "priorytet",
          "progress": "harmonogram",
          "resource": "ratunek",
          "note": "Uwaga",
          "attachment": "załącznik",
          "word": "Słowo"
        },
        "error_message": {
          "title": "Ups, mapa myśli poszła nie tak",
          "err_load": "Nie udało się załadować mapy myśli",
          "err_save": "Nie udało się zapisać mapy myśli",
          "err_network": "Błąd sieci",
          "err_doc_resolve": "Analiza dokumentu nie powiodła się",
          "err_unknown": "stało się coś dziwnego",
          "err_localfile_read": "błąd odczytu pliku",
          "err_download": "Pobieranie pliku nie powiodło się",
          "err_remove_share": "Nie udało się cofnąć udostępniania",
          "err_create_share": "udostępnianie nie powiodło się",
          "err_mkdir": "Tworzenie katalogu nie powiodło się",
          "err_ls": "Nie udało się odczytać katalogu",
          "err_share_data": "Błąd ładowania udostępnionej zawartości",
          "err_share_sync_fail": "Synchronizacja udostępnionej zawartości nie powiodła się",
          "err_move_file": "Przenoszenie pliku nie powiodło się",
          "err_rename": "Zmiana nazwy nie powiodła się",
          "unknownreason": "Może kosmici sfałszowali kod...",
          "pcs_code": {
            "3": "Ten interfejs nie jest obsługiwany",
            "4": "Nie masz uprawnień do wykonania tej operacji",
            "5": "IP nie jest autoryzowane",
            "110": "Sesja użytkownika wygasła, zaloguj się ponownie",
            "31001": "błąd zapytania do bazy danych",
            "31002": "błąd połączenia z bazą danych",
            "31003": "Baza danych zwraca puste wyniki",
            "31021": "Błąd sieci",
            "31022": "Chwilowo nie można połączyć się z serwerem",
            "31023": "błędny parametr wejściowy",
            "31024": "identyfikator aplikacji jest pusty",
            "31025": "błąd pamięci zaplecza",
            "31041": "Plik cookie użytkownika nie jest legalnym plikiem cookie Baidu",
            "31042": "użytkownik niezalogowany",
            "31043": "Użytkownik nie jest aktywny",
            "31044": "użytkownik nie jest autoryzowany",
            "31045": "użytkownik nie istnieje",
            "31046": "Użytkownik już istnieje",
            "31061": "Plik już istnieje",
            "31062": "nielegalna Nazwa pliku",
            "31063": "Katalog nadrzędny pliku nie istnieje",
            "31064": "nie masz uprawnień dostępu do tego pliku",
            "31065": "katalog pełny",
            "31066": "plik nie istnieje",
            "31067": "błąd przetwarzania pliku",
            "31068": "Tworzenie pliku nie powiodło się",
            "31069": "Kopiowanie pliku nie powiodło się",
            "31070": "Usuwanie pliku nie powiodło się",
            "31071": "Nie można odczytać metainformacji o pliku",
            "31072": "Przenoszenie pliku nie powiodło się",
            "31073": "Zmiana nazwy pliku nie powiodła się",
            "31079": "Nie znaleziono pliku MD5. Użyj interfejsu API przesyłania, aby przesłać cały plik.",
            "31081": "utworzenie superpliku nie powiodło się",
            "31082": "lista zablokowanych superplików jest pusta",
            "31083": "aktualizacja superpliku nie powiodła się",
            "31101": "wewnętrzny błąd systemu tagów",
            "31102": "błąd parametru tagu",
            "31103": "błąd systemu tagów",
            "31110": "Brak uprawnień do ustawiania limitu dla tego katalogu",
            "31111": "Zarządzanie limitami obsługuje tylko katalogi dwupoziomowe",
            "31112": "Mozliwa ilość przekroczona",
            "31113": "Limit nie może przekroczyć limitu przodków katalogu",
            "31114": "Limit nie może być mniejszy niż limit podkatalogu",
            "31141": "Żądanie usługi miniaturek nie powiodło się",
            "31201": "błąd podpisu",
            "31202": "plik nie istnieje",
            "31203": "Nie udało się ustawić acl",
            "31204": "Żądanie weryfikacji acl nie powiodło się",
            "31205": "Nie udało się uzyskać acl",
            "31206": "acl nie istnieje",
            "31207": "wiadro już istnieje",
            "31208": "błąd żądania użytkownika",
            "31209": "błąd serwera",
            "31210": "serwer nie obsługuje",
            "31211": "Brak dostępu",
            "31212": "usługa nie jest dostępna",
            "31213": "spróbuj ponownie w przypadku błędu",
            "31214": "Nie udało się przesłać danych pliku",
            "31215": "Nie udało się przesłać pliku meta",
            "31216": "Nie udało się pobrać danych pliku",
            "31217": "Nie udało się pobrać pliku meta",
            "31218": "Pojemność przekroczona",
            "31219": "Liczba żądań przekracza limit",
            "31220": "Przekroczono limit ruchu",
            "31298": "Serwer zwraca nieprawidłowy KLUCZ",
            "31299": "Wartość zwrócona przez serwer KLUCZ nie istnieje"
          }
        },
        "ui": {
          "shared_file_title": "[udostępniony] {0} (tylko do odczytu)",
          "load_share_for_edit": "Ładowanie udostępnionego pliku...",
          "share_sync_success": "Udostępniona zawartość została zsynchronizowana",
          "recycle_clear_confirm": "Czy na pewno chcesz opróżnić kosz? ",
          "fullscreen_exit_hint": "Naciśnij Esc lub F11, aby wyjść z pełnego ekranu",
          "error_detail": "Detale",
          "copy_and_feedback": "kopiować i przekazywać informacje zwrotne",
          "move_file_confirm": "Czy na pewno chcesz przenieść „{0}” do „{1}”?",
          "rename": "Przemianować",
          "rename_success": "{0} pomyślnie zmieniono nazwę",
          "move_success": "{0} pomyślnie przeniesiono do {1}",
          "command": {
            "appendsiblingnode": "wstaw temat rodzeństwa",
            "appendparentnode": "wstaw temat nadrzędny",
            "appendchildnode": "Wstaw temat podrzędny",
            "removenode": "usuwać",
            "editnode": "edytować",
            "arrangeup": "Podnieść",
            "arrangedown": "padnij",
            "resetlayout": "Zorganizuj układ",
            "expandtoleaf": "Rozwiń wszystkie węzły",
            "expandtolevel1": "Rozwiń do poziomu pierwszego węzła",
            "expandtolevel2": "Rozwiń do węzłów drugorzędnych",
            "expandtolevel3": "Rozwiń do węzłów trzeciego poziomu",
            "expandtolevel4": "Rozwiń do węzłów czteropoziomowych",
            "expandtolevel5": "Rozwiń do węzłów pięciopoziomowych",
            "expandtolevel6": "Rozwiń do węzłów sześciopoziomowych",
            "fullscreen": "pełny ekran",
            "outline": "zarys",
            "addtag": "Dodać do"
          },
          "search": "szukaj",
          "expandtoleaf": "zwiększać",
          "back": "powrót",
          "undo": "Cofnij (Ctrl + Z)",
          "redo": "Ponów (Ctrl + Y)",
          "tabs": {
            "idea": "TOK myślenia",
            "appearence": "Zewnętrzny",
            "view": "pogląd"
          },
          "quickvisit": {
            "new": "Nowy (Ctrl + Alt + N)",
            "save": "Zapisz (Ctrl + S)",
            "share": "Udostępnij (Ctrl + Alt + S)",
            "feedback": "Pytania zwrotne (F1)",
            "editshare": "edytować"
          },
          "menu": {
            "mainmenutext": "Mapa mózgu Baidu",
            "newtab": "nowo zbudowane",
            "opentab": "otwarty",
            "savetab": "ratować",
            "sharetab": "udział",
            "preferencetab": "organizować coś",
            "helptab": "pomoc",
            "feedbacktab": "informacje zwrotne",
            "recenttab": "Ostatnio używany",
            "netdisktab": "Przechowywanie w chmurze Baidu",
            "localtab": "pliki lokalne",
            "drafttab": "pudełko projektowe",
            "downloadtab": "wyeksportuj do lokalnego",
            "createsharetab": "aktualna mapa myśli",
            "managesharetab": "wspólny",
            "newheader": "Stwórz nową mapę myśli",
            "openheader": "otwarty",
            "saveheader": "Zapisz do",
            "draftheader": "pudełko projektowe",
            "shareheader": "udostępnij moją mapę myśli",
            "downloadheader": "Eksportuj do określonego formatu",
            "preferenceheader": "Preferencje",
            "helpheader": "pomoc",
            "feedbackheader": "informacje zwrotne"
          },
          "mydocument": "mój dokument",
          "emptydir": "Katalog jest pusty!",
          "pickfile": "Wybierz dokument...",
          "acceptfile": "Obsługiwane formaty: {0}",
          "dropfile": "lub przeciągnij pliki tutaj",
          "unsupportedfile": "niewspierany format pliku",
          "untitleddoc": "nienazwany dokument",
          "overrideconfirm": "{0} już istnieje, czy na pewno chcesz zastąpić?",
          "checklogin": "Sprawdzanie stanu logowania...",
          "loggingin": "Logowanie...",
          "recent": "niedawno otwarty",
          "clearrecent": "pusty",
          "clearrecentconfirm": "Czy na pewno chcesz wyczyścić listę ostatnich dokumentów?",
          "cleardraft": "pusty",
          "cleardraftconfirm": "Czy na pewno chcesz wyczyścić okno wersji roboczej?",
          "none_share": "nie publikuj",
          "public_share": "udostępniać publicznie",
          "password_share": "udostępnianie prywatne",
          "email_share": "zaproszenie e-mail",
          "url_share": "Adres URL mapy myśli:",
          "sns_share": "Udostępnij w sieciach społecznościowych:",
          "sns_share_text": "„{0}” — mapa myśli, którą stworzyłem za pomocą Baidu Brain Map, spójrz! ",
          "none_share_description": "Nie udostępniaj aktualnej mapy myśli",
          "public_share_description": "Twórz akcje widoczne dla każdego",
          "share_button_text": "tworzyć",
          "password_share_description": "Twórz udziały, które wymagają hasła, aby były widoczne",
          "email_share_description": "Twórz udziały, które są widoczne dla określonych osób, a także możesz zezwolić im na edycję",
          "ondev": "Czekać na dalsze informacje!",
          "create_share_failed": "Udostępnianie nie powiodło się: {0}",
          "remove_share_failed": "Usuwanie nie powiodło się: {1}",
          "copy": "Kopiuj",
          "copied": "skopiowane",
          "shared_tip": "Aktualna mapa myśli jest udostępniana przez {0}, możesz ją zmodyfikować i zapisać na własnym dysku sieciowym lub udostępnić ponownie",
          "current_share": "aktualna mapa myśli",
          "manage_share": "moja część",
          "share_remove_action": "Nie udostępniaj tej mapy myśli",
          "share_view_action": "Otwórz adres udostępniania",
          "share_edit_action": "Edytuj udostępnione pliki",
          "login": "Zaloguj sie",
          "logout": "Wyloguj",
          "switchuser": "Przełącz konto",
          "userinfo": "informacje osobiste",
          "gotonetdisk": "mój dysk sieciowy",
          "requirelogin": "Proszę <a class=\"login-button\">zalogować się</a>, aby użyć",
          "saveas": "Zapisz jako",
          "filename": "Nazwa pliku",
          "fileformat": "zapisz format",
          "save": "ratować",
          "mkdir": "nowy katalog",
          "recycle": "kosz",
          "newdir": "nienazwany katalog",
          "bold": "pogrubiony",
          "italic": "kursywa",
          "forecolor": "kolor czcionki",
          "fontfamily": "czcionka",
          "fontsize": "rozmiar czcionki",
          "layoutstyle": "temat",
          "node": "działanie węzła",
          "saveto": "Zapisz jako",
          "hand": "Zezwalaj na przeciąganie",
          "camera": "zlokalizować węzeł główny",
          "zoom-in": "Powiększ (Ctrl+)",
          "zoom-out": "Pomniejsz (Ctrl-)",
          "markers": "Etykieta",
          "resource": "ratunek",
          "help": "pomoc",
          "preference": "Preferencje",
          "expandnode": "rozłożyć na liście",
          "collapsenode": "Zwiń do węzła pierwszego poziomu",
          "template": "szablon",
          "theme": "skóra",
          "clearstyle": "jasny styl",
          "copystyle": "styl kopiowania",
          "pastestyle": "wklej styl",
          "appendsiblingnode": "temat rodzeństwa",
          "appendchildnode": "temat podrzędny",
          "arrangeup": "górna nuta",
          "arrangedown": "po tonie",
          "editnode": "edytować",
          "removenode": "usunąć",
          "priority": "priorytet",
          "removepriority": "usunąć priorytet",
          "progress": {
            "p1": "jeszcze się nie zaczął",
            "p2": "1/8 zrobione",
            "p3": "1/4 zrobione",
            "p4": "3/8 zrobione",
            "p5": "w połowie zrobione",
            "p6": "Gotowe 5/8",
            "p7": "3/4 zrobione",
            "p8": "Gotowe 7/8",
            "p9": "zakończony",
            "p0": "wyraźny postęp"
          },
          "link": "Połączyć",
          "image": "zdjęcie",
          "note": "Uwaga",
          "insertlink": "wstaw link",
          "insertimage": "wstaw obrazek",
          "insertnote": "wstaw notatkę",
          "removelink": "usunąć istniejący link",
          "removeimage": "usunąć istniejący obraz",
          "removenote": "usuń istniejącą notatkę",
          "resetlayout": "czysty",
          "justnow": "Tylko",
          "minutesago": "{0} minut temu",
          "hoursago": "{0} godzin temu",
          "yesterday": "Wczoraj",
          "daysago": "{0} dni temu",
          "longago": "Dawno temu",
          "redirect": "Otwierasz połączenie {0}, Baidu Brain Map nie może zagwarantować bezpieczeństwa połączenia, czy chcesz kontynuować?",
          "navigator": "Nawigator",
          "unsavedcontent": "Bieżący plik nie został zapisany na dysku sieciowym:\n\n",
          "shortcuts": "Klawisz skrótu",
          "contact": "Kontakt i opinie",
          "email": "grupa pocztowa",
          "qq_group": "Grupa QQ",
          "github_issue": "Github",
          "baidu_tieba": "pasek pocztowy",
          "clipboardunsupported": "Twoja przeglądarka nie obsługuje schowka, użyj klawisza skrótu, aby skopiować",
          "load_success": "{0} załadowano pomyślnie",
          "save_success": "{0} został zapisany w dniu {1}",
          "autosave_success": "{0} został automatycznie zapisany w dniu {1}",
          "selectall": "Zaznacz wszystko",
          "selectrevert": "wybory odwrotne",
          "selectsiblings": "Wybierz węzeł równorzędny",
          "selectlevel": "Wybierz węzły równorzędne",
          "selectpath": "wybierz ścieżkę",
          "selecttree": "wybierz poddrzewo"
        },
        "popupcolor": {
          "clearColor": "jasny kolor",
          "standardColor": "standardowy kolor",
          "themeColor": "kolor motywu"
        },
        "dialogs": {
          "markers": {
            "static": {
              "lang_input_text": "Treść tekstu:",
              "lang_input_url": "adres linku:",
              "lang_input_title": "tytuł:",
              "lang_input_target": "Czy w nowym oknie:"
            },
            "priority": "priorytet",
            "none": "nic",
            "progress": {
              "title": "harmonogram",
              "notdone": "nie spełniony",
              "done1": "1/8 zrobione",
              "done2": "1/4 zrobione",
              "done3": "3/8 zrobione",
              "done4": "1/2 zrobione",
              "done5": "Gotowe 5/8",
              "done6": "3/4 zrobione",
              "done7": "Gotowe 7/8",
              "done": "zakończony"
            }
          },
          "help": {},
          "hyperlink": {},
          "image": {},
          "resource": {}
        },
        "hyperlink": {
          "hyperlink": "Połączyć...",
          "unhyperlink": "usuń łącze"
        },
        "image": {
          "image": "zdjęcie...",
          "removeimage": "usuń obraz"
        },
        "marker": {
          "marker": "Postęp/Priorytet..."
        },
        "resource": {
          "resource": "ratunek..."
        }
    },
    'de':{
        "template": {
          "default": "Mind-Mapping",
          "tianpan": "Himmelskarte",
          "structure": "Organigramm",
          "filetree": "Verzeichnis-Organigramm",
          "right": "Logisches Strukturdiagramm",
          "fish-bone": "Fischgrätendiagramm"
        },
        "hotbox": {
          "undo": "widerrufen",
          "redo": "wiederholen",
          "appendsiblingnode": "auf demselben Level",
          "appendparentnode": "Vorgesetzter",
          "appendchildnode": "untergeordnet",
          "editnode": "bearbeiten",
          "arrangeup": "Bewegen Sie sich nach oben",
          "arrangedown": "sich abwärts bewegen",
          "resetlayout": "Organisieren Sie das Layout",
          "remove": "löschen",
          "priority": "Priorität",
          "progress": "Zeitplan",
          "importnode": "Knoten importieren",
          "exportnode": "Knoten exportieren"
        },
        "theme": {
          "classic": "Brain Map Classic",
          "classic-compact": "kompakter Klassiker",
          "snow": "Sanftes kaltes Licht",
          "snow-compact": "Kompaktes Kaltlicht",
          "fish": "Fishbone-Diagramm",
          "wire": "Drahtmodell",
          "fresh-red": "frisches rot",
          "fresh-soil": "Erde gelb",
          "fresh-green": "Literarisches Grün",
          "fresh-blue": "Himmelblau",
          "fresh-purple": "romantisches lila",
          "fresh-pink": "Gehirnpulver",
          "fresh-red-compat": "kompaktes rot",
          "fresh-soil-compat": "kompakt gelb",
          "fresh-green-compat": "kompaktes grün",
          "fresh-blue-compat": "kompakt blau",
          "fresh-purple-compat": "kompaktes lila",
          "fresh-pink-compat": "kompaktes Pulver",
          "tianpan": "Klassisches Gericht",
          "tianpan-compact": "Kompaktes Gericht"
        },
        "maintopic": "zentrales Thema",
        "topic": "Zweig Thema",
        "panels": {
          "history": "Geschichte",
          "template": "Vorlage",
          "theme": "Haut",
          "layout": "Layout",
          "style": "Stil",
          "font": "Wort",
          "color": "Farbe",
          "background": "Hintergrund",
          "insert": "Einfügung",
          "arrange": "Einstellung",
          "nodeop": "aktuell",
          "priority": "Priorität",
          "progress": "Zeitplan",
          "resource": "Ressource",
          "note": "Anmerkung",
          "attachment": "Anhang",
          "word": "Wort"
        },
        "error_message": {
          "title": "Hoppla, die Mindmap ist schief gelaufen",
          "err_load": "Mindmap konnte nicht geladen werden",
          "err_save": "Mindmap konnte nicht gespeichert werden",
          "err_network": "Netzwerkfehler",
          "err_doc_resolve": "Dokumentanalyse fehlgeschlagen",
          "err_unknown": "etwas Komisches ist passiert",
          "err_localfile_read": "Fehler beim Lesen der Datei",
          "err_download": "Dateidownload fehlgeschlagen",
          "err_remove_share": "Freigabe aufheben fehlgeschlagen",
          "err_create_share": "Teilen fehlgeschlagen",
          "err_mkdir": "Verzeichniserstellung fehlgeschlagen",
          "err_ls": "Verzeichnis konnte nicht gelesen werden",
          "err_share_data": "Fehler beim Laden freigegebener Inhalte",
          "err_share_sync_fail": "Synchronisierung freigegebener Inhalte fehlgeschlagen",
          "err_move_file": "Dateiverschiebung fehlgeschlagen",
          "err_rename": "Umbenennen fehlgeschlagen",
          "unknownreason": "Vielleicht haben Aliens den Code manipuliert...",
          "pcs_code": {
            "3": "Diese Schnittstelle wird nicht unterstützt",
            "4": "Sie haben keine Berechtigung, diesen Vorgang auszuführen",
            "5": "IP ist nicht autorisiert",
            "110": "Die Benutzersitzung ist abgelaufen, bitte melden Sie sich erneut an",
            "31001": "Datenbankabfrage Fehler",
            "31002": "Datenbankverbindungsfehler",
            "31003": "Die Datenbank gibt leere Ergebnisse zurück",
            "31021": "Netzwerkfehler",
            "31022": "Verbindung zum Server vorübergehend nicht möglich",
            "31023": "falscher Eingabeparameter",
            "31024": "App-ID ist leer",
            "31025": "Backend-Speicherfehler",
            "31041": "Das Cookie des Benutzers ist kein legitimes Baidu-Cookie",
            "31042": "Benutzer nicht eingeloggt",
            "31043": "Benutzer ist nicht aktiv",
            "31044": "Der Nutzer ist nicht berechtigt",
            "31045": "Benutzer existiert nicht",
            "31046": "Benutzer existiert bereits",
            "31061": "Die Datei existiert bereits",
            "31062": "illegaler Dateiname",
            "31063": "Das übergeordnete Verzeichnis der Datei existiert nicht",
            "31064": "keine Berechtigung zum Zugriff auf diese Datei haben",
            "31065": "Verzeichnis voll",
            "31066": "Die Datei existiert nicht",
            "31067": "Dateiverarbeitungsfehler",
            "31068": "Dateierstellung fehlgeschlagen",
            "31069": "Kopieren der Datei fehlgeschlagen",
            "31070": "Löschen der Datei fehlgeschlagen",
            "31071": "Metainformationen der Datei konnten nicht gelesen werden",
            "31072": "Dateiverschiebung fehlgeschlagen",
            "31073": "Dateiumbenennung fehlgeschlagen",
            "31079": "Datei MD5 nicht gefunden, bitte verwenden Sie die Upload-API, um die gesamte Datei hochzuladen.",
            "31081": "Superfile-Erstellung fehlgeschlagen",
            "31082": "Superfile-Blockliste ist leer",
            "31083": "Superfile-Update fehlgeschlagen",
            "31101": "Interner Fehler des Tag-Systems",
            "31102": "Tag-Parameterfehler",
            "31103": "Tag-Systemfehler",
            "31110": "Keine Berechtigung zum Festlegen des Kontingents für dieses Verzeichnis",
            "31111": "Die Kontingentverwaltung unterstützt nur Verzeichnisse mit zwei Ebenen",
            "31112": "Quote überschritten",
            "31113": "Das Kontingent darf das Kontingent der Verzeichnisvorfahren nicht überschreiten",
            "31114": "Das Kontingent darf nicht kleiner sein als das Kontingent des Unterverzeichnisses",
            "31141": "Fehler beim Anfordern des Thumbnail-Dienstes",
            "31201": "Signaturfehler",
            "31202": "Die Datei existiert nicht",
            "31203": "acl konnte nicht eingestellt werden",
            "31204": "ACL-Verifizierung anfordern fehlgeschlagen",
            "31205": "acl konnte nicht abgerufen werden",
            "31206": "acl existiert nicht",
            "31207": "Eimer existiert bereits",
            "31208": "Benutzeranforderungsfehler",
            "31209": "Serverfehler",
            "31210": "Server nicht unterstützt",
            "31211": "Kein Zugang",
            "31212": "Service ist nicht verfügbar",
            "31213": "bei Fehler erneut versuchen",
            "31214": "Dateidaten konnten nicht hochgeladen werden",
            "31215": "Datei-Meta konnte nicht hochgeladen werden",
            "31216": "Dateidaten konnten nicht heruntergeladen werden",
            "31217": "Dateimeta konnte nicht heruntergeladen werden",
            "31218": "Kapazität überschritten",
            "31219": "Die Anzahl der Anfragen überschreitet das Limit",
            "31220": "Verkehrslimit überschritten",
            "31298": "Der Server gibt einen ungültigen KEY zurück",
            "31299": "Der vom Server zurückgegebene Wert KEY existiert nicht"
          }
        },
        "ui": {
          "shared_file_title": "[geteilt] {0} (schreibgeschützt)",
          "load_share_for_edit": "Freigegebene Datei wird geladen...",
          "share_sync_success": "Freigegebene Inhalte wurden synchronisiert",
          "recycle_clear_confirm": "Möchten Sie den Papierkorb wirklich leeren? ",
          "fullscreen_exit_hint": "Drücken Sie Esc oder F11, um den Vollbildmodus zu verlassen",
          "error_detail": "Einzelheiten",
          "copy_and_feedback": "Kopie und Feedback",
          "move_file_confirm": "Möchten Sie \"{0}\" wirklich nach \"{1}\" verschieben?",
          "rename": "Umbenennen",
          "rename_success": "{0} erfolgreich umbenannt",
          "move_success": "{0} erfolgreich nach {1} verschoben",
          "command": {
            "appendsiblingnode": "Geschwisterthema einfügen",
            "appendparentnode": "Oberthema einfügen",
            "appendchildnode": "Unterthema einfügen",
            "removenode": "löschen",
            "editnode": "bearbeiten",
            "arrangeup": "Bewegen Sie sich nach oben",
            "arrangedown": "sich abwärts bewegen",
            "resetlayout": "Organisieren Sie das Layout",
            "expandtoleaf": "Erweitern Sie alle Knoten",
            "expandtolevel1": "Erweitern Sie den Knoten auf Ebene eins",
            "expandtolevel2": "Erweitern Sie auf sekundäre Knoten",
            "expandtolevel3": "Erweitern Sie auf Knoten der dritten Ebene",
            "expandtolevel4": "Erweitern Sie auf Knoten mit vier Ebenen",
            "expandtolevel5": "Erweitern Sie auf Knoten mit fünf Ebenen",
            "expandtolevel6": "Erweitern Sie auf Knoten mit sechs Ebenen",
            "fullscreen": "Vollbild",
            "outline": "Umriss",
            "addtag": "ergänzen"
          },
          "search": "suchen",
          "expandtoleaf": "expandieren",
          "back": "zurückkehren",
          "undo": "Rückgängig (Strg + Z)",
          "redo": "Wiederherstellen (Strg + Y)",
          "tabs": {
            "idea": "Gedankengang",
            "appearence": "Außen",
            "view": "Sicht"
          },
          "quickvisit": {
            "new": "Neu (Strg + Alt + N)",
            "save": "Speichern (Strg + S)",
            "share": "Teilen (Strg + Alt + S)",
            "feedback": "Feedback-Fragen (F1)",
            "editshare": "bearbeiten"
          },
          "menu": {
            "mainmenutext": "Baidu-Gehirnkarte",
            "newtab": "Neubau",
            "opentab": "Offen",
            "savetab": "speichern",
            "sharetab": "Aktie",
            "preferencetab": "aufstellen",
            "helptab": "Hilfe",
            "feedbacktab": "die Rückmeldung",
            "recenttab": "Kürzlich benutzt",
            "netdisktab": "Baidu-Cloud-Speicher",
            "localtab": "lokale Dateien",
            "drafttab": "Entwurfsbox",
            "downloadtab": "Export nach lokal",
            "createsharetab": "aktuelle Mindmap",
            "managesharetab": "geteilt",
            "newheader": "Erstellen Sie eine neue Mindmap",
            "openheader": "Offen",
            "saveheader": "Speichern unter",
            "draftheader": "Entwurfsbox",
            "shareheader": "teile meine Mindmap",
            "downloadheader": "In das angegebene Format exportieren",
            "preferenceheader": "Einstellungen",
            "helpheader": "Hilfe",
            "feedbackheader": "die Rückmeldung"
          },
          "mydocument": "Mein Dokument",
          "emptydir": "Verzeichnis ist leer!",
          "pickfile": "Dokument auswählen...",
          "acceptfile": "Unterstützte Formate: {0}",
          "dropfile": "oder ziehen Sie Dateien hierher",
          "unsupportedfile": "nicht unterstütztes Dateiformat",
          "untitleddoc": "Unbenanntes Dokument",
          "overrideconfirm": "{0} existiert bereits, möchten Sie wirklich überschreiben?",
          "checklogin": "Anmeldestatus prüfen...",
          "loggingin": "Einloggen...",
          "recent": "vor kurzem eröffnet",
          "clearrecent": "leer",
          "clearrecentconfirm": "Möchten Sie die Liste der zuletzt verwendeten Dokumente wirklich löschen?",
          "cleardraft": "leer",
          "cleardraftconfirm": "Möchten Sie das Entwurfsfeld wirklich leeren?",
          "none_share": "nicht teilen",
          "public_share": "öffentlich teilen",
          "password_share": "privates Teilen",
          "email_share": "E-Mail-Einladung",
          "url_share": "Mindmap-URL-Adresse:",
          "sns_share": "In sozialen Netzwerken teilen:",
          "sns_share_text": "\"{0}\" - Die Mindmap, die ich mit Baidu Brain Map erstellt habe, schau sie dir an! ",
          "none_share_description": "Teilen Sie nicht die aktuelle Mindmap",
          "public_share_description": "Erstellen Sie Freigaben, die für jeden sichtbar sind",
          "share_button_text": "erstellen",
          "password_share_description": "Erstellen Sie Freigaben, für deren Sichtbarkeit ein Kennwort erforderlich ist",
          "email_share_description": "Erstellen Sie Freigaben, die für bestimmte Personen sichtbar sind, und Sie können ihnen auch die Bearbeitung erlauben",
          "ondev": "Bleiben Sie dran!",
          "create_share_failed": "Teilen fehlgeschlagen: {0}",
          "remove_share_failed": "Löschen fehlgeschlagen: {1}",
          "copy": "Kopieren",
          "copied": "kopiert",
          "shared_tip": "Die aktuelle Mind Map wird von {0} geteilt, Sie können sie ändern und auf Ihrer eigenen Netzwerkfestplatte speichern oder erneut teilen",
          "current_share": "aktuelle Mindmap",
          "manage_share": "mein Anteil",
          "share_remove_action": "Teilen Sie diese Mindmap nicht",
          "share_view_action": "Freigabeadresse öffnen",
          "share_edit_action": "Freigegebene Dateien bearbeiten",
          "login": "Anmeldung",
          "logout": "Ausloggen",
          "switchuser": "Benutzer wechseln",
          "userinfo": "Persönliche Angaben",
          "gotonetdisk": "meine Netzwerkfestplatte",
          "requirelogin": "Bitte <a class=\"login-button\">anmelden</a> um es zu verwenden",
          "saveas": "Speichern als",
          "filename": "Dateinamen",
          "fileformat": "Format speichern",
          "save": "speichern",
          "mkdir": "neues Verzeichnis",
          "recycle": "Papierkorb",
          "newdir": "unbenanntes Verzeichnis",
          "bold": "deutlich",
          "italic": "Kursivschrift",
          "forecolor": "Schriftfarbe",
          "fontfamily": "Schriftart",
          "fontsize": "Schriftgröße",
          "layoutstyle": "Thema",
          "node": "Knotenbetrieb",
          "saveto": "Speichern als",
          "hand": "Ziehen zulassen",
          "camera": "Suchen Sie den Root-Knoten",
          "zoom-in": "Vergrößern (Strg+)",
          "zoom-out": "Verkleinern (Strg-)",
          "markers": "Etikett",
          "resource": "Ressource",
          "help": "Hilfe",
          "preference": "Einstellungen",
          "expandnode": "auf die Blätter ausbreiten",
          "collapsenode": "Auf den Knoten der ersten Ebene reduzieren",
          "template": "Vorlage",
          "theme": "Haut",
          "clearstyle": "klarer Stil",
          "copystyle": "Stil kopieren",
          "pastestyle": "Stil einfügen",
          "appendsiblingnode": "Geschwister Thema",
          "appendchildnode": "untergeordnetes Thema",
          "arrangeup": "Top-Note",
          "arrangedown": "nach ton",
          "editnode": "bearbeiten",
          "removenode": "entfernen",
          "priority": "Priorität",
          "removepriority": "Priorität entfernen",
          "progress": {
            "p1": "hat nicht begonnen",
            "p2": "1/8 fertig",
            "p3": "1/4 fertig",
            "p4": "3/8 fertig",
            "p5": "halb fertig",
            "p6": "Fertig 5/8",
            "p7": "3/4 fertig",
            "p8": "Fertig 7/8",
            "p9": "vollendet",
            "p0": "deutlicher Fortschritt"
          },
          "link": "Verknüpfung",
          "image": "Bild",
          "note": "Anmerkung",
          "insertlink": "Link einfügen",
          "insertimage": "Bild einfügen",
          "insertnote": "Notiz einfügen",
          "removelink": "bestehenden Link entfernen",
          "removeimage": "vorhandenes Bild entfernen",
          "removenote": "vorhandene Notiz entfernen",
          "resetlayout": "aufgeräumt",
          "justnow": "Nur",
          "minutesago": "vor {0} Minuten",
          "hoursago": "vor {0} Stunden",
          "yesterday": "gestern",
          "daysago": "vor {0} Tagen",
          "longago": "Vor langer Zeit",
          "redirect": "Sie öffnen die Verbindung {0}, Baidu Brain Map kann die Sicherheit der Verbindung nicht garantieren, möchten Sie fortfahren?",
          "navigator": "Navigator",
          "unsavedcontent": "Die aktuelle Datei wurde nicht auf der Netzwerkfestplatte gespeichert:\n\n",
          "shortcuts": "Hotkey",
          "contact": "Kontakt und Feedback",
          "email": "Mailgruppe",
          "qq_group": "QQ-Gruppe",
          "github_issue": "GitHub",
          "baidu_tieba": "Postbar",
          "clipboardunsupported": "Ihr Browser unterstützt die Zwischenablage nicht, bitte verwenden Sie die Tastenkombination zum Kopieren",
          "load_success": "{0} erfolgreich geladen",
          "save_success": "{0} wurde am {1} gespeichert",
          "autosave_success": "{0} wurde automatisch am {1} gespeichert",
          "selectall": "Wählen Sie Alle",
          "selectrevert": "umgekehrte Wahl",
          "selectsiblings": "Wählen Sie einen gleichgeordneten Knoten aus",
          "selectlevel": "Wählen Sie Geschwisterknoten aus",
          "selectpath": "Weg wählen",
          "selecttree": "Teilbaum auswählen"
        },
        "popupcolor": {
          "clearColor": "klare Farbe",
          "standardColor": "Standardfarbe",
          "themeColor": "Themenfarbe"
        },
        "dialogs": {
          "markers": {
            "static": {
              "lang_input_text": "Textinhalt:",
              "lang_input_url": "Linkadresse:",
              "lang_input_title": "Titel:",
              "lang_input_target": "Ob in einem neuen Fenster:"
            },
            "priority": "Priorität",
            "none": "keiner",
            "progress": {
              "title": "Zeitplan",
              "notdone": "rückgängig gemacht",
              "done1": "1/8 fertig",
              "done2": "1/4 fertig",
              "done3": "3/8 fertig",
              "done4": "1/2 fertig",
              "done5": "Fertig 5/8",
              "done6": "3/4 fertig",
              "done7": "Fertig 7/8",
              "done": "vollendet"
            }
          },
          "help": {},
          "hyperlink": {},
          "image": {},
          "resource": {}
        },
        "hyperlink": {
          "hyperlink": "Verknüpfung...",
          "unhyperlink": "Verknüpfung entfernen"
        },
        "image": {
          "image": "Bild...",
          "removeimage": "entferne Bild"
        },
        "marker": {
          "marker": "Fortschritt/Priorität..."
        },
        "resource": {
          "resource": "Ressource..."
        }
    }
};
